### ISSUE TITLE
SAFARI -Version 15.3 (16612.4.9.1.7, 16612)

### ISSUE THREAD

**Issue by izzicp** [KBLiveSolutions/open.control#9]
Hello,
I just received my Boxed open.control.
But I can't connect using SAFARI Version 15.3 (16612.4.9.1.7, 16612) (Mac OS 11.6.3)
But CHROME works well Version 98.0.4758.102 (Build officiel) (x86_64)
just annoying when SAFARI is the default web browser!

May be it's just an adjustment to do ??
Does somebody have the same behavior ?

Regards, Cesare

**Comment by KBLiveSolutions** [comment]
Hi Cesare

Unfortunately, Safari doesn't support WebMIDI, which is the framework used for the editor.
As stated in the Get Started page, the browsers that support it are Chrome, Edge and Opera.

I might do a Max For Live version of the editor someday, but for now it has to be one of these browsers, sorry.

**Comment by KBLiveSolutions** [comment]
This might help :
https://www.macintoshhowto.com/internet/how-to-open-a-url-in-a-certain-browser.html
